### ISSUE TITLE
attachments: `glob` doesn't glob as expected (Replace globs with filters)

### ISSUE THREAD

**Issue by eins78** [cider-ci/cider-ci#2]
[Not sure which sub-service is responsible for this]

edge-case, very low priority (if I ever really need this I'll zip the folder ;))

---

test spec snippet:
```yaml
tasks:
- name: features styleguide
  trial_attachments:
    styleguide-screenshots:
      glob: 'tmp/styleguide-ref/*/*.png'
      content-type: image/png
```
[Result: does not match anything](http://ci2.zhdk.ch/cider-ci/ui/workspace/trials/2791b80e-6da4-438a-8b95-517058c83946/attachments)

---

picking a sub-folder (sanity check):
```yaml
glob: 'tmp/styleguide-ref/Combos/*.png'
```
Result: matches everything in subfolder

---

btw, also doesn't work:
```yaml
glob: 'tmp/styleguide-ref/**/*.png'
```
