### ISSUE TITLE
Support more/all settings for configured repositories. 

### ISSUE THREAD

**Issue by pape-io** [cider-ci/cider-ci#22]
`git_fetch_and_update_interval` and `github_authtoken` seems to not get applied:

```
repositories:
  - name: xxx
    git_url: xxx
    git_fetch_and_update_interval: 10
    github_authtoken: 1234
```

When I check the result in the UI its 60 seconds and no auth token
