### ISSUE TITLE
v4: Load is 16, but just 1 is dispatched at a time

### ISSUE THREAD

**Issue by pape-io** [cider-ci/cider-ci#36]
I even removed all exclusive resource definitions, but nothing helped.

![screen shot 2016-04-29 at 12 26 08](https://cloud.githubusercontent.com/assets/851393/14913776/ad05fbc4-0e05-11e6-9018-140283dde841.png)
![screen shot 2016-04-29 at 12 26 18](https://cloud.githubusercontent.com/assets/851393/14913779/aefeaed0-0e05-11e6-8b81-4913199ab110.png)

```
---
key: rspec
name: RSPec tests
run-on:
- type: branch
  include-match: "^.*$"
context:
  tasks:
    spec/data/raw_spec.rb:
      key: data/raw_spec.rb
      name: data/raw_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/data/raw_spec.rb
    spec/data/item_spec.rb:
      key: data/item_spec.rb
      name: data/item_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/data/item_spec.rb
    spec/data/root_spec.rb:
      key: data/root_spec.rb
      name: data/root_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/data/root_spec.rb
    spec/item/save_spec.rb:
      key: item/save_spec.rb
      name: item/save_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/item/save_spec.rb
    spec/data/merge_spec.rb:
      key: data/merge_spec.rb
      name: data/merge_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/data/merge_spec.rb
    spec/proxy/load_spec.rb:
      key: proxy/load_spec.rb
      name: proxy/load_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/proxy/load_spec.rb
    spec/record/all_spec.rb:
      key: record/all_spec.rb
      name: record/all_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/all_spec.rb
    spec/record/new_spec.rb:
      key: record/new_spec.rb
      name: record/new_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/new_spec.rb
    spec/data/select_spec.rb:
      key: data/select_spec.rb
      name: data/select_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/data/select_spec.rb
    spec/item/errors_spec.rb:
      key: item/errors_spec.rb
      name: item/errors_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/item/errors_spec.rb
    spec/item/getter_spec.rb:
      key: item/getter_spec.rb
      name: item/getter_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/item/getter_spec.rb
    spec/item/setter_spec.rb:
      key: item/setter_spec.rb
      name: item/setter_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/item/setter_spec.rb
    spec/item/update_spec.rb:
      key: item/update_spec.rb
      name: item/update_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/item/update_spec.rb
    spec/record/find_spec.rb:
      key: record/find_spec.rb
      name: record/find_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/find_spec.rb
    spec/record/save_spec.rb:
      key: record/save_spec.rb
      name: record/save_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/save_spec.rb
    spec/data/to_json_spec.rb:
      key: data/to_json_spec.rb
      name: data/to_json_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/data/to_json_spec.rb
    spec/item/destroy_spec.rb:
      key: item/destroy_spec.rb
      name: item/destroy_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/item/destroy_spec.rb
    spec/record/build_spec.rb:
      key: record/build_spec.rb
      name: record/build_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/build_spec.rb
    spec/record/first_spec.rb:
      key: record/first_spec.rb
      name: record/first_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/first_spec.rb
    spec/record/where_spec.rb:
      key: record/where_spec.rb
      name: record/where_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/where_spec.rb
    spec/item/delegate_spec.rb:
      key: item/delegate_spec.rb
      name: item/delegate_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/item/delegate_spec.rb
    spec/record/create_spec.rb:
      key: record/create_spec.rb
      name: record/create_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/create_spec.rb
    spec/record/select_spec.rb:
      key: record/select_spec.rb
      name: record/select_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/select_spec.rb
    spec/record/find_by_spec.rb:
      key: record/find_by_spec.rb
      name: record/find_by_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/find_by_spec.rb
    spec/record/mapping_spec.rb:
      key: record/mapping_spec.rb
      name: record/mapping_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/mapping_spec.rb
    spec/record/request_spec.rb:
      key: record/request_spec.rb
      name: record/request_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/request_spec.rb
    spec/record/to_json_spec.rb:
      key: record/to_json_spec.rb
      name: record/to_json_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/to_json_spec.rb
    spec/views/form_for_spec.rb:
      key: views/form_for_spec.rb
      name: views/form_for_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/views/form_for_spec.rb
    spec/data/collection_spec.rb:
      key: data/collection_spec.rb
      name: data/collection_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/data/collection_spec.rb
    spec/data/respond_to_spec.rb:
      key: data/respond_to_spec.rb
      name: data/respond_to_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/data/respond_to_spec.rb
    spec/item/respond_to_spec.rb:
      key: item/respond_to_spec.rb
      name: item/respond_to_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/item/respond_to_spec.rb
    spec/item/validation_spec.rb:
      key: item/validation_spec.rb
      name: item/validation_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/item/validation_spec.rb
    spec/record/includes_spec.rb:
      key: record/includes_spec.rb
      name: record/includes_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/includes_spec.rb
    spec/endpoint/for_url_spec.rb:
      key: endpoint/for_url_spec.rb
      name: endpoint/for_url_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/endpoint/for_url_spec.rb
    spec/record/endpoints_spec.rb:
      key: record/endpoints_spec.rb
      name: record/endpoints_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/endpoints_spec.rb
    spec/record/find_each_spec.rb:
      key: record/find_each_spec.rb
      name: record/find_each_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/find_each_spec.rb
    spec/record/persisted_spec.rb:
      key: record/persisted_spec.rb
      name: record/persisted_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/persisted_spec.rb
    spec/record/model_name_spec.rb:
      key: record/model_name_spec.rb
      name: record/model_name_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/model_name_spec.rb
    spec/record/pagination_spec.rb:
      key: record/pagination_spec.rb
      name: record/pagination_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/pagination_spec.rb
    spec/record/definitions_spec.rb:
      key: record/definitions_spec.rb
      name: record/definitions_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/definitions_spec.rb
    spec/collection/delegate_spec.rb:
      key: collection/delegate_spec.rb
      name: collection/delegate_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/collection/delegate_spec.rb
    spec/collection/meta_data_spec.rb:
      key: collection/meta_data_spec.rb
      name: collection/meta_data_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/collection/meta_data_spec.rb
    spec/collection/enumerable_spec.rb:
      key: collection/enumerable_spec.rb
      name: collection/enumerable_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/collection/enumerable_spec.rb
    spec/collection/respond_to_spec.rb:
      key: collection/respond_to_spec.rb
      name: collection/respond_to_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/collection/respond_to_spec.rb
    spec/pagination/pages_left_spec.rb:
      key: pagination/pages_left_spec.rb
      name: pagination/pages_left_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/pagination/pages_left_spec.rb
    spec/record/creation_failed_spec.rb:
      key: record/creation_failed_spec.rb
      name: record/creation_failed_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/creation_failed_spec.rb
    spec/record/find_in_batches_spec.rb:
      key: record/find_in_batches_spec.rb
      name: record/find_in_batches_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/find_in_batches_spec.rb
    spec/collection/configurable_spec.rb:
      key: collection/configurable_spec.rb
      name: collection/configurable_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/collection/configurable_spec.rb
    spec/record/endpoint_options_spec.rb:
      key: record/endpoint_options_spec.rb
      name: record/endpoint_options_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/endpoint_options_spec.rb
    spec/collection/collection_items_spec.rb:
      key: collection/collection_items_spec.rb
      name: collection/collection_items_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/collection/collection_items_spec.rb
    spec/item/internal_data_structure_spec.rb:
      key: item/internal_data_structure_spec.rb
      name: item/internal_data_structure_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/item/internal_data_structure_spec.rb
    spec/record/paginatable_collection_spec.rb:
      key: record/paginatable_collection_spec.rb
      name: record/paginatable_collection_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/paginatable_collection_spec.rb
    spec/collection/without_object_items_spec.rb:
      key: collection/without_object_items_spec.rb
      name: collection/without_object_items_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/collection/without_object_items_spec.rb
    spec/record/endpoint_misconfiguration_spec.rb:
      key: record/endpoint_misconfiguration_spec.rb
      name: record/endpoint_misconfiguration_spec.rb
      traits: {}
      environment_variables:
        CIDER_CI_TASK_FILE: spec/record/endpoint_misconfiguration_spec.rb
  task_defaults:
    ports:
      CAPYBARA_PORT:
        max: 8999
        min: 8000
        inet_address: localhost
      PHANTOMJS_PORT:
        max: 44999
        min: 44600
        inet_address: localhost
    traits: {}
    scripts:
      ruby:
        body: |
          #!/usr/bin/env bash
          export PATH=~/.rbenv/bin:$PATH
          eval "$(rbenv init -)"
          if [ ! -d ${HOME}/.rbenv/versions/${RBENV_VERSION} ]; then
            rbenv install ${RBENV_VERSION}
            gem install bundler
          fi
          rbenv local ${RBENV_VERSION}
          ruby --version
          export PATH=~/.rbenv/bin:$PATH
          eval "$(rbenv init -)"
          echo $(rbenv which bundle)
          $(rbenv which bundle)
        timeout: 20 Minutes
        environment-variables:
          RBENV_VERSION: 2.1.0
      rspec:
        start-when:
        - script: ruby
        - script: tmp-cache
      tmp-cache:
        body: mkdir -p tmp/cache
    trial-attachments:
      logs:
        content-type: text/plain
        include-match: log\/.*\.log$
      html-screenshots:
        content-type: text/html
        include-match: tmp\/capybara\/.*\.html$
      image-screenshots:
        content-type: image/png
        include-match: tmp\/capybara\/.*\.png$
empty_tasks_warning: true
```
