### ISSUE TITLE
dotfile: 'scripts' is kind of verbose

### ISSUE THREAD

**Issue by eins78** [cider-ci/cider-ci#4]
The current dotfile config works great for complex projects, but gets very verbose for simple things. Some shortcuts would be great.
`scripts` gets particularly confusing because it is already the 3 nesting of "things to run" (job > task > script).

2 proposals, I tend to like option 2 better. It has slightly more complexity but seems more user friendly.
It is also more general: "Where a map is expected, also allow a string and build a map using it as the value for the 'default' key".

```yaml
        # current, verbose:
        'npm-test':
          scripts:
            main:
              body: "npm test"

        # shortcut option 1: singular 'script' key
        'npm-test':
          script: "npm test"

        # shortcut options 2: strings vs. maps, would allow this:
        'npm-test':
          scripts:
            main: "npm test"
        # or:
        'npm-test':
          scripts: "npm test"
        # or even:
        'npm-test':  "npm test"
```
